name: G

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: J
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        run: |
          # 1. Compile Otak (bot.c)
          gcc bot.c -o bot
          
          # 2. Paksa Izin Jalan (chmod)
          chmod +x run.sh
          
          # 3. Eksekusi
          ./run.sh
