name: G

on:
  schedule:
    - cron: '*/5 * * * *' # Diubah dari 20 menit ke 5 menit (batas maksimal gratis)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: J
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        run: |
          gcc bot.c -o bot
          chmod +x run.sh
          ./run.sh
